// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Ismarlin2018_0846.DAL;

namespace P2_AP1_Ismarlin2018_0846.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211207032259_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Ismarlin2018_0846.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("P2_AP1_Ismarlin2018_0846.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimientos")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDetalle");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("P2_AP1_Ismarlin2018_0846.Entidades.TipoTareas", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoTarea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoId");

                    b.ToTable("TipoTareas");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            FechaIngreso = new DateTime(2021, 12, 7, 23, 22, 53, 868, DateTimeKind.Local).AddTicks(8823),
                            TiempoTarea = 0,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoId = 2,
                            FechaIngreso = new DateTime(2021, 12, 7, 23, 22, 53, 944, DateTimeKind.Local).AddTicks(2862),
                            TiempoTarea = 0,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoId = 3,
                            FechaIngreso = new DateTime(2021, 12, 7, 23, 22, 53, 944, DateTimeKind.Local).AddTicks(3005),
                            TiempoTarea = 0,
                            TipoTarea = "Programacion"
                        },
                        new
                        {
                            TipoId = 4,
                            FechaIngreso = new DateTime(2021, 12, 7, 23, 22, 53, 944, DateTimeKind.Local).AddTicks(3020),
                            TiempoTarea = 0,
                            TipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_Ismarlin2018_0846.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("P2_AP1_Ismarlin2018_0846.Entidades.Proyectos", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2_AP1_Ismarlin2018_0846.Entidades.Proyectos", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
